title: ApproxiPong
description: "An informal review of reinfocement learning algorithms using deep learning methods."

markdown: kramdown
theme: minima

baseurl: "/ApproxiPong"
url: "https://jonathanfiat.github.io"
permalink: "/:title"

google_analytics: UA-112637451-1

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

disqus:
  shortname: approxipong
