title: ApproxiPong
description: "An informal review of reinfocement learning algorithms using deep learning methods."

markdown: kramdown
theme: minima

baseurl: "/ApproxiPong"
url: "https://jonathanfiat.github.io"
production_url: "https://jonathanfiat.github.io"

google_analytics: UA-112637451-1

plugins:
  - jekyll-seo-tag

disqus:
  shortname: approxipong
